# Generated by Django 4.1.2 on 2022-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_info_alter_post_tittle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_info',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
