# Generated by Django 4.1.2 on 2022-10-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tittle',
            field=models.CharField(max_length=100),
        ),
    ]
