# Generated by Django 4.1.2 on 2022-10-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_image_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
