# Generated by Django 4.1.2 on 2022-10-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
