# Generated by Django 4.1.2 on 2022-10-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_student_info_post_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
